/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Balary Docs",
  "tagline": "Private payroll powered by confidential compute.",
  "favicon": "https://res.cloudinary.com/dsbmr3xin/image/upload/v1786656190/bi_scp3ev.png",
  "url": "https://docs.balary.lol",
  "baseUrl": "/",
  "organizationName": "balary",
  "projectName": "balary-docs",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "docs"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/balary-logo.png",
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Balary Docs",
      "logo": {
        "alt": "Balary B logo",
        "src": "img/balary-logo.png",
        "srcDark": "img/balary-logo.png"
      },
      "items": [
        {
          "to": "/docs/intro",
          "label": "Docs",
          "position": "left"
        },
        {
          "label": "Product",
          "position": "left",
          "items": [
            {
              "to": "/docs/product-overview/what-is-balary",
              "label": "What is Balary?"
            },
            {
              "to": "/docs/product-overview/why-confidential-payroll",
              "label": "Why confidential payroll"
            },
            {
              "to": "/docs/product-overview/user-journeys",
              "label": "User journeys"
            }
          ]
        },
        {
          "label": "Confidential Compute",
          "position": "left",
          "items": [
            {
              "to": "/docs/fcc-integration/overview",
              "label": "FCC overview"
            },
            {
              "to": "/docs/fcc-integration/instruction-flow",
              "label": "Instruction flow"
            },
            {
              "to": "/docs/fcc-integration/tee-lifecycle",
              "label": "TEE lifecycle"
            }
          ]
        },
        {
          "label": "Build",
          "position": "left",
          "items": [
            {
              "to": "/docs/api-reference/overview",
              "label": "API reference"
            },
            {
              "to": "/docs/architecture/overview",
              "label": "Architecture"
            },
            {
              "to": "/docs/deployment/coston2",
              "label": "Deployment"
            }
          ]
        },
        {
          "href": "https://github.com/Sparexonzy95/balary",
          "label": "GitHub ↗",
          "position": "right"
        },
        {
          "href": "https://balary.lol",
          "label": "Open Balary ↗",
          "position": "right",
          "className": "navbar-open-balary"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting started",
              "to": "/docs/getting-started"
            },
            {
              "label": "Employer guide",
              "to": "/docs/employer/overview"
            },
            {
              "label": "Employee guide",
              "to": "/docs/employee/overview"
            }
          ]
        },
        {
          "title": "Build",
          "items": [
            {
              "label": "API reference",
              "to": "/docs/api-reference/overview"
            },
            {
              "label": "Architecture",
              "to": "/docs/architecture/overview"
            },
            {
              "label": "Security",
              "to": "/docs/security/privacy-model"
            },
            {
              "label": "Verification",
              "to": "/docs/verification/test-evidence"
            }
          ]
        },
        {
          "title": "Network",
          "items": [
            {
              "label": "Developer Hub",
              "href": "https://dev.flare.network/"
            },
            {
              "label": "FCC overview",
              "href": "https://dev.flare.network/fcc/overview"
            },
            {
              "label": "Coston2 explorer",
              "href": "https://coston2-explorer.flare.network"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Balary"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "python",
        "typescript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "throw",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
